[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "OpenQAS"
version = "0.0.7"
description = "Question and Answer Sheet editor"
readme = "README.md"
license = { text = "GPL-3.0" }
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Topic :: Education",
    "Topic :: Software Development :: Libraries"
]

dependencies = [
    "sympy",
    "antlr4-python3-runtime==4.11",
    "PyQt5>=5.15.0"
]

[project.optional-dependencies]
docx = [
    "odfpy"
]
dev = [
    "pytest",
    "pytest-qt",
    "pytest-cov",
    "pylint",
    "flake8"
]

[project.urls]
Repository = "https://github.com/Wolf359Stella/OpenQAS"


[tool.pylint.messages_control]
disable = [
    "C0302",  # Too many lines in module
    "R0903",  # Too few public methods
    "W1202",  # Use % formatting in logging functions
    "W1203",  # Use lazy % or .format() formatting
    "W0511",  # TODOs
    "W0223",  # Abstract method not overridden
    "R0912",
    "E0401",
    "W0122"
]

[tool.pylint.design]
max-attributes = 20
max-args = 20
max-bool-expr = 15
max-statements = 100


[tool.basedpyright]
reportExplicitAny = false
reportUnusedCallResult = "none"
reportMissingTypeStubs = "none"
